* GFTool-Electron

translation: [[https://github.com/Kreedzt/GFTool-Electron/blob/master/README_CN.org][中文]]

This project is [[https://github.com/hycdes/GFTool][GFTool]] electron version.

It experience better for offline use

More version info: See [[https://github.com/Kreedzt/GFTool-Electron/blob/master/CHANGELOG.org][Changelog]]

Tips:
This project is currently *NOT STABLE*, if you found some bug or have some
advice, please open an issue(paste your log file content).

** RoadMap

  - [X] manual update
  - [X] manual open log file
  - [X] Clipboard crashed
  - [X] Auto update page(web)
  - [X] Auto detected update software
  - [X] Add proxy config
  - [ ] Auto open log when application crashed

** Build
   You must have *nodejs* environment first, See [[https://nodejs.org/en/][Nodejs]] to how to install.

   1. Install dependencies
      #+begin_src shell
        # This project use yarn.lock file to lock dependencies, so i recommanded to use yarn install package
        # use yarn
        yarn
      #+end_src

      or
      #+begin_src shell
        npm i
      #+end_src

   2. Add your GithubToken to ~src/config.js~
      #+begin_src js
        const AccessToken = 'Your token(detal to Bearer) here'
      #+end_src

   3. Clone web page
      #+begin_src shell
        git clone https://github.com/hycdes/GFTool.git web/ --depth=1
      #+end_src

   4. Initialize env
      when you don't have ~/config~ folder, run this command
      #+begin_src shell
        npm run initialize-config
      #+end_src

      set config version
      #+begin_src shell
        npm run tag-version
      #+end_src

   5. Start dev:
      #+begin_src shell
        npm run start
      #+end_src

   6. Build for Windows:
      #+begin_src shell
        npm run build:win
      #+end_src

   7. Build for MacOS:
      #+begin_src shell
        npm run build:mac
      #+end_src

** Install and Usage

   Install:
   1. Requirements:
      This software use *git* for *manual update*, if your pc not have it, the manual update menu will *NOT EFFECT*
      So if you want to use *manual update* menu, your pc must have installed [[https://git-scm.com/][git]].

   2. Go to [[https://github.com/Kreedzt/GFTool-Electron/releases][release]] page to download lastest build.
      For windows, download ~exe~ file(Tested on Windows 10 1909)
      For MacOS, download ~dmg~ file(Tested on MacOS 10.13.6)


   *NOTICE*: Because of electron limit, you *MUST* use *short cut* instead of
   web pages "Copy" or "Paste" button.

   See Edit menu

   Usage:
   Menus(For MacOS, Check your Title bar):
   - Test(Or GFTool-Electron(The app name))
     + Get lastest web page version: get lastest web page commit info
   - Edit(Override web contents clipboard, which is very *IMPORANT*)
     + SelectAll: shorcut: ~Ctrl+A~ or ~Cmd+A~
     + Cut: shorcut: ~Ctrl+X~ or ~Cmd+X~
     + Copy: shorcut: ~Ctrl+C~ or ~Cmd+C~
     + Paste: shorcut: ~Ctrl+V~ or ~Cmd+V~
   - Actions
     + Copy url Path: copy the link address to your clipboard
     + Open current link: open link external(By your browser)
   - Config
     + Proxy: set http request proxy address(This effect update request)
   - View
     + Reload: Reload The Web page
     + Toggle Full Screen
     + Toggle Developer Tools: open chrome devtools(For debug if you are sure
       what you are doing)
   - About
     + Manual Update Page: Manual pull code from [[https://github.com/hycdes/GFTool][GFTool]] (using git)
     + Open Logs file: open the application logs(for issue usage)

** License
   [[https://github.com/Kreedzt/GFTool-Electron/blob/master/LICENSE][MIT]]
